stages:
    - debug-build
    - release-build
    - doc-build

opensuse-doc-build:
    stage: doc-build
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo doc
    artifacts:
        paths:
            - target/doc
        expire_in: 2d
    only:
        - release
        - web

opensuse-development-build:
    stage: debug-build
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo build
    artifacts:
        paths:
            - target/debug/backend
            - target/debug/worker
            - target/debug/dispatcher
    only:
        - debug
        - web

debian-development-build:
    stage: debug-build
    image: dnegi/asta-astaprint-build:buster-latest
    script:
        - cargo build 
    artifacts:
        paths:
            - target/debug/backend
            - target/debug/worker
            - target/debug/dispatcher
    only:
        - debug
        - web

opensuse-release-build:
    stage: release-build
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2d
    only:
        - release
        - web

debian-release-build:
    stage: release-build
    image: dnegi/asta-astaprint-build:buster-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2d
    only:
        - release
        - web
