
stages:
    - build

build:
    stage: build
    image: opensuse/leap
    script:
        - zypper --non-interactive install curl libpoppler-glib-devel libmariadb-devel libsodium-devel
        - zypper --non-interactive install -t pattern devel_basis
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y
        - source  $HOME/.cargo/env
        - rustc --version && cargo --version
        - rustup override set nightly
        - cargo test --all --verbose
        - cargo build
        - cargo build --release
    artifacts:
        paths:
            - target/debug/backend
            - target/debug/worker
            - target/debug/dispatcher
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 1 week
