
stages:
    - build

build-openSuse:
    stage: build
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2 days
        only: 
            - master
            - release

build-debian: 
    stage: build
    image: dnegi/asta-astaprint-build:buster-latest
    script:
        cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2 days
        only: 
            - master
            - release
