
stages:
    - build

build:
    stage: build
    image: dnegi/asta-astaprint-build:latest
    script:
        - cargo build
        - cargo build --release
    artifacts:
        paths:
            - target/debug/backend
            - target/debug/worker
            - target/debug/dispatcher
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 1 week
