stages:
    - build-Debian
    - build-openSuse

build-openSuse:
    stage: build-openSuse
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 1 week
    only:
        - release

build-Debian:
    stage: build-Debian
    image: dnegi/asta-astaprint-build:buster-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 1 week
    only:
        - release
