
stages:
    - build-release

build-openSuse:
    stage: build-release
    image: dnegi/asta-astaprint-build:leap-latest
    script:
        - cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2 days

build-debian: 
    stage: build-release
    image: dnegi/asta-astaprint-build:buster-latest
    script:
        cargo build --release
    artifacts:
        paths:
            - target/release/backend
            - target/release/worker
            - target/release/dispatcher
        expire_in: 2 days

