[package]
name = "astaprint"
version = "0.1.0"
authors = ["Gerrit Pape <gerrit.pape@asta.upb.de>"]

[workspace]
members = ["dispatcher", "worker", "backend"]

[dependencies]
log = {version = "*", features = ["std", "max_level_debug", "release_max_level_info"]}
chrono = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
netsnmp-sys = "*"
diesel = {version = "*", features = ["mysql", "r2d2", "chrono", "bigdecimal", "numeric"]}
r2d2 = "*"
bigdecimal = "*"
sha2 = "*"

