[package]
name = "astaprint"
version = "0.1.0"
authors = ["Gerrit Pape <gerrit.pape@asta.upb.de>"]

[dependencies]
astacrypto = {path = "./crypto"}
redis = {path = "./redis"}
logger = {path = "./logger"}
log = {version = "*", features = ["std", "max_level_debug", "release_max_level_info"]}
chrono = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
bincode = "*"
netsnmp-sys = "*"
diesel = {version = "*", features = ["mysql", "r2d2", "chrono", "bigdecimal", "numeric"]}
r2d2_redis = "*"
threadpool = "*"
bigdecimal = "0.0.11"
rocket = "*"
rocket_contrib = "*"
rocket_codegen = "*"
rocket_cors = "*"
maxminddb = "*"
base64 = "*"
lpr = "0.1.4"
cairo-rs = { version= "0.3.0", features = ["png"]}
poppler = {git = "https://git.uni-paderborn.de/asta/poppler-rs", rev="69ea0bc"}
