edition = "2018"
version = "Two"
ignore = [
       "src/jobs/mod.rs",
]
license_template_path = "license.template"
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
wrap_comments = true
use_small_heuristics = "Off"
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = false
fn_single_line = true
where_single_line = false
imports_layout = "Vertical"
merge_imports = true
reorder_impl_items = true
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = true
combine_control_expr = false
struct_field_align_threshold = 0
force_multiline_blocks = true
brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
trailing_semicolon = false
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
force_explicit_abi = true
condense_wildcard_suffixes = true
color = "Always"
unstable_features = false
overflow_delimited_expr = true
skip_children = false
error_on_line_overflow = true
error_on_unformatted = true
report_todo = "Always"
report_fixme = "Always"
