[package]
name = "snmp"
version = "0.1.0"
authors = ["Gerrit Pape <papeg@mail.upb.de>"]
edition = "2018"

[dependencies]
netsnmp-sys = "0.1"
mysql = {path = "../mysql"}
diesel = {version = "1.3", features = ["mysql", "r2d2"]}
