[package]
name = "mysql"
version = "0.1.0"
authors = ["Gerrit Pape <papeg@mail.upb.de>"]
edition = "2018"

[dependencies]
diesel = {version = "1.4", features = ["mysql", "r2d2", "chrono"]}
chrono = "0.4"
bincode = "1.1"
